[W06] DualPivotQuicksortTests
JohannesStoehr/gad23-tests pull request #38
Opened 2023-06-14 12:29 UTC by YifanChen03

### Checklist
#### General

- [ ] I confirm that my tests, if any, are correct
    - [ ] Optional: I pass **all** artemis tests.
    - [ ] Optional: I pass **all** tests, that are added in this PR.
    - [ ] Optional: I calculated manually the correct solutions on paper.
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://github.com/JohannesStoehr/gad23-tests/blob/main/CONTRIBUTING.md).
- [ ] The newly added tests do not reveal the solutions dynamically calculating the solutions as expected in the exercise.
- [ ] Other students approved this Pull Request.

### Description

2023-06-14 16:15 UTC, Flnn0 requested changes
Code LGTM but the part that you have to remove the logging from your original code isn't good. Maybe you could implemten it as myself in PR #35 with the an `StudentResultTest` class. It's much easier for the others and there is no risk to forget to put the logging back in.

2023-06-15 18:29 UTC, YifanChen03 commented
> Code LGTM but the part that you have to remove the logging from your original code isn't good. Maybe you could implemten it as myself in PR #35 with the an `StudentResultTest` class. It's much easier for the others and there is no risk to forget to put the logging back in.

added a class StudentResultForTest.java to simplify testing

2023-06-16 04:11 UTC, Flnn0 requested changes

2023-06-16 04:11 UTC, Flnn0 commented on w06/test/gad/DualPivotQuicksortTest.java
> +        StudentResult result = new StudentResultForTest();
You have to change `StudentResult` to `StudentResultForTest` otherways you get a error.

2023-06-16 04:11 UTC, Flnn0 commented on w06/test/gad/DualPivotQuicksortTest.java
> +        StudentResult result = new StudentResult();
Here it's the same as in Line `157`. Especially in this Test the logging is rising the runtime and this caused that some devices might not finish this test.

2023-06-16 04:11 UTC, Flnn0 commented on w06/test/gad/StudentResultForTest.java
> +    public void logArray(int[] array) {}
This isn't the logging method of this exercise. Have a look in `StudentResult` which is given from Artemis.

2023-06-20 10:19 UTC, closed without merging