[W01] Add test case executor
JohannesStoehr/gad23-tests pull request #9
Opened 2023-04-19 17:46 UTC by Anatoly03

### Checklist
#### General

- [ ] I locally pass **all** tests or calculated manually the correct solutions on paper.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://github.com/JohannesStoehr/gad23-tests/blob/main/CONTRIBUTING.md).
- [x] The newly added tests do not reveal the solutions dynamically calculating the solutions as expected in the exercise.

### Description

- add `cases.txt`: Text Format of Test Case Data
- add `TestExecutor.java` Add Test Case Collector & Test Case Executor

### Review Progress

#### Review
- [ ] Review 1
- [ ] Optional Review 2

2023-04-19 17:48 UTC, Anatoly03 commented
Note with this PR:  I locally **DO NOT** pass all tests due to an IDE error, **BUT** calculated manually the correct solutions on paper. I'd still prefer not to check that box before other students will be able to tell me for safety.

2023-04-19 18:42 UTC, Anatoly03 commented
The current test cases have been added:

```
200 - 10 - 9
▌▀▜▀▀▀▀▛▀▛▜▛▀▀▜▀▛▛▀█▛▛▜▜▀▜▀▀▜▛▀▀▀▀▛▀▀▛▛▀▀▀▜▀▀▀▀▀▀▀▜▀▛█▛▜▀█▀▀▀▜▜▜▜▀▀▀█▜▛▜▛▀▜▀▀▀▛▜▀▀▛█▀▀▀▀▀▛▀▜▀▀▀▛▀▀▀▜
▌▀▞▝▀▗▝  ▝▗▌▚▝▗▙▗  ▞▖▗  ▄▘ ▞ ▗▖▖▐▐▝    ▜▟▄▝▘  ▄ ▝ ▟▗ ▐▝▘▖▐   ▝▝ ▗▘▖▐▖▐ ▖▄▐▝  ▗▛▘ ▚▛▞▛▞▖▘ ▌▖▗▝▘▚▜▐▖ ▐
▙ ▘ ▌▝▌▗ ▄▝ ▗▟▀   ▝▌ ▚  ▐ ▙ ▘▀▐▝▘▖▚▗▘▗ ▀▘▘▗▌  ▘▖▗▘▚  ▖▖▌▘▞▖ ▘ ▞ ▝▄▖ ▖▝▟ ▞▝▝▘▘  ▖▗▖▙▘▖ ▐▟▚▖▖ ▖█▘  ▗▄▐
▙▝▐ ▗ ▚ ▖▖▌▖ ▝▝  ▘▖  ▖ ▐▖▝   ▗▌ ▖ ▙▘ ▖▄   ▗▘▖  ▘▄ ▗ ▐▞▝▗▘ ▖▜▖▘ ▐▖▖▄▞▝▚▗▝▝    ▘▘   ▗▗▌▗ ▚▚▌   ▀▖▘  ▖▐
▙▟█▟▟▟▄▙▟▄▙▟█▙█▄▄▄▙▄▄▄▄▄▟█▄▙▄▟▄▟▄▄▄▄▄▄▙▄▄▙▟▟▟▟▙▙█▟▟▙▄▟▄█▙▄▙▟▄▄▄▟▄▙▄▄▄▄▙▄▄▄▄▙▟▟▄▟▟▟▙▟█▙▄▄▄▄▙▄▄▟▟▟▄▄▄▄
```

```
200 - 10 - 6
▌▀█▛▛▜▛▀▀▜▀▀▀▀▛▀▀▛▀▛▛▀▀▀▀▀▀▀▀▜▛█▀▛▀▀▛█▀▀▀▜▀▀█▛▛▛▛▀▀▛▀▀▀▛▀▀▀▛▀▀▛▜▀▀▀▛▀▀▀▀▀▛▀▀▀▀█▀▛█▜▀▀▜▜▀▀▜▛▀▀▀▀▀▀▛▛▜
▌▝▌ ▝▘▟▄▞▗▌▄▖▟▝▜▖▗▖  ▘▙▙ ▖▘▚ ▝▗▐▀  ▖  ▝▖▝ ▘▖▄ ▖  ▘ ▗▚▘▐▙▐ ▀ ▐▖ ▖ ▗▜ ▗ ▄▝ ▐  ▖▘▘ ▘▌▖▚▝ ▖ ▚▗▐▖  ▛ ▞▘▖▐
▙▄▐▝▘     ▟▝▘▝▝▘▖ ▘▄ ▖  ▖▝▚  ▜ ▝▖ ▖▗ ▖▌▜▘ ▗▀ ▘ ▘▘ ▗▖ ▞▗ ▝  ▞▘ ▘ ▀ ▖ ▘▄▚ ▝▖▝▖▝▝▙▚▞▗ ▟▚ ▝▖▄▀▖▘ ▘▞▗▝ ▟▐
▛▗▝▚▞▐▀▄ ▗  ▖▝▘    ▚▀▞▄▗▐▗▀ ▘█ ▚▌▝▙▚▌▐ ▘▖▘ ▄  ▐   ▖ ▙▘▜ ▖  ▝ ▌▘▗█▘  ▘▚▞  ▀▘▚▗ ▀▐▘▝▝▟▗▀ ▗▖▗▛ ▛ ▌▖▞▚▘▟
▙▄▄▄▄▄▄▟▙▄▄█▄▄▙▟▄▄▄█▟▄▄▄▙▙▄▟▟▄▄▄▄▟▄▄▙▙▄▄▄▟▄▄▟▄▄▄▄▄▄▟▟▄▙▟▟▄▙▄▄▟▄▟▄▟▙▄█▄▄▟▄▙▄▄▄▄▙▄▄▄▄▟▄▄▄▄▄▟█▙▄▙▟▄▄▄▙▄
```

```
200 - 50 - 9
▌▀▀▀█▀▀▀▜▀▀▜▜▀▛▀▀▀▀▛▀▛▛▜▜▀▜▀▀▀▀▜▀▀▀▜▀▀▀▀▜▜▀▀▀▀▛▜█▀▀▀▛█▀▀▛▀▀▛▜▛█▀▛▀▀▀▀▀▀▜▀█▜▛▀▛▛▜▀▀█▀▀▀▛▀▜▀▀▛▀▀▜▜▀▀▀█
▛ ▗▌▖▀▟ ▞ ▖▜▝▜▗▗▝▖▞▘▄▗▚ ▗  ▖ ▚ ▐  ▜▟ ▝ ▞▚▖▘ ▖▘▖▜▝ ▐ ▝ ▞▖▖▜ ▌▖▝▀▖▌▐▌▐▄▖▗▖ ▘▖▘▚▞ ▌▗▝ ▝▘▀▝ ▘▛▝ ▝▞▖▖▖ ▞▜
▌▗▗    ▗▚ ▘▛▀▖▞▘▗▐▖▗▀▀▝  ▐▐▖▄ ▘▗▝ ▝▘  ▄▗▗▀▐ ▗ ▘▗ ▞▘▞▘ ▗▘ ▝▗ ▝▝ ▝▚ ▗▗▖█  ▘▗ ▚ ▐ ▌  ▘▄▖▖▝▖▝ ▖ ▀▄▗▚▝▞▖▐
█ ▌   ▌▘▗ ▐ ▖▞▝ ▗▗ ▘▌▗ ▚▖▗ ▖▝ ▗ ▘ ▐▘  ▛  █▖▞  ▚ ▗▘ ▘▖▝ ▝▝▄▌▗▄▌▝ ▚▗▐ ▘ ▘  ▗▐  ▝▛ ▚▘  ▐ ▖ ▝ ▘ ▖▚ ▗▞ ▖▐
▛▗▀  ▌▖ ▞▗ ▘ ▚▘▀ ▘▘ ▘▚▄▘▄▗▘▌▐▀▝▞ ▗▀▚▝ ▖ ▛ ▖▞▖ ▘ ▖▘ ▚ ▗  ▖▐▙▘▝▖▖▗▄▝▘▘▗ ▘▗ ▗ ▄▗▀▗▗ ▘▗▛▀ ▘  ▖ ▜ ▌▄▀▘ ▗▐
▌▘▖ ▝▖ ▜▝ ▄▖ ▗ ▗▚▘▘ ▄▀▗ ▝▖ ▄ ▄▝ ▗▝▛▞▞▖ ▝▝  ▝     ▖ ▝▌▝▝▖ ▌▝ ▘▖  ▝▝ ▞▛▐▚ ▘▄  ▖ ▘▘▐  ▗▗ ▞▛▗ ▖▗▝▘ ▗▚▝▖▐
▌▖▖▖    ▛ ▌  ▗ ▐▗▘▝▌    ▘ ▗▖ ▗▝▘▝▗ ▗ ▗▘ ▐▐▗▄ ▘▝▌▚ ▞ ▞▗   ▗▝ ▘▝▗▝▘ ▖▐ ▖▗▗▘▝▗▗▘▀▖ ▞▘▝▖▐▙ ▀  ▖▌▝▐▌  ▚▚▟
▌▘▚  ▝▙▖▐ ▄▗ ▄▌ ▞▝▐▗ ▖▗▝▝▗ ▝▗▞ ▄▝   ▀▗▚▗▄▝▚  ▘  ▚▘ ▄▄▀▘  ▘▝▖   ▘ ▝ ▖▜ ▀▀▌▌▖▝▘▚▝▝▗▖▖▚▐  ▚▖▖▙▝  ▖▝  ▘▟
▌▗ ▗ ▘ ▗▝▗▄▄  ▖▝ ▞▝▗ ▐▀ ▝▗▘ ▚▖▀▖▗▄    ▖▚▀▗▄▘▗▗▚  ▘▝▗▖▝▐▌▝▝ ▗▘▄ ▘▜▖▚ ▝▛▘▘ ▗▌▘ ▀▖  ▗▖▗ ▘█ ▞  ▀▄▖▗▜ ▙▞▜
▙▘▟▟▄▘ ▝▖▀▘▜▖ ▗ ▚ ▖▘▖▘▖▖█ ▗▘  ▝▛▝▀█▘ ▝▝▘▖ ▘▞   ▘ ▖▗ ▄▌ ▐▙▗ ▗▟▖▘   ▖▞▄▖▞ ▘▖ ▝  ▗▗▖▟▌  ▖ ▖▌▗▛▖ ▗▘ ▗▖ ▐
▌▘▌▌▄▚▝   ▚▘▚▗ ▀▐▀▀ ▗ ▜▟▝ ▖▖▖ ▌▘▄▗▟ ▘ ▞▚ ▖▀▐▝▗▝▖▘▐▝▘▝▞ ▖▖ ▚ ▘ ▖▝▚▝▗▞▘▘▖▘  ▞▄  ▗▘ ▌▘▝▗▞ ▗▚▌▘▖▖▗▖▘▀▘▄▟
▛ ▛   ▟ ▖▞▐▖ ▖▟▝▀▖   ▝▜▖▗▘ ▗▘▜ ▖  ▘▖▞  ▖▄▝▗▖ ▘  ▗▝  ▗ ▘▐ ▘▘ ▗▖▗▖▙▖▀    ▝▗▜▗▞█ ▗▄▚▝▝  ▗▗     ▘▗ ▜▙ ▝▐
▌▌▐▝▘▌ ▘▘▚ ▘ ▖▝▘▖▗▐▗ ▐▚▜▝ ▖     ▛▗▘▚▝  ▀ ▖▗▗▚▛  ▗ ▝  ▘ ▖▘   ▀▝▘▘ ▝  ▖▟▄ ▖ ▗  ▘▝▘▝▖▗▖▖ ▖▝▀   ▐▘▌▝ ▝▘▐
▌▘▞ ▟  ▗ ▗▝▘▜▞  ▗▗▝ ▚▀   ▞▌▖▞▚ ▖▘ ▖▀▘▄  ▝ ▖▖ ▘  ▘   ▄▘▗▗ ▘  ▗▗▗▗ ▝▘ ▚▞▖▝▝▗ ▗ ▗ ▘▟▐ ▖▙▀▗▚▝▘  ▚▘▗▘▛ ▝▟
█▐ ▖ ▗▖ ▛▀▀▘▝▖  ▞ ▝▖▗▜▖   ▐▘  ▝▄ ▗▝▗▗▘▗▘ ▄▀▗▗ ▘ ▌ ▝ ▛▝▝▖ ▝  ▖  ▞  ▌▀ ▘ ▝▖▗▝▘ ▚▖▐▀▝▘▗▟ ▐▗ ▀ ▖ ▝▗▝▜ ▘▜
▛▐▝▗ ▐▚▘ ▝▗ ▛▘▞▀▘▗▖▘▗█▝    ▄▞▄▄▘▗▖▗▙ ▝▚▗▄▄  ▖▘▘▖▝▝  ▖▄▞▖▘▙▘▖▝▖ ▝ ▙▞ ▗▘▘ ▖▝▘ ▀  ▘▞▝▙  ▖▜ ▘▞▖ ▖  ▘▟ ▘▟
▛▘ ▄▄  ▝▖▖▖ ▘  ▝▟▐▞▌ ▘ ▖▀▝ ▖▗ ▞▖▀▄▖▐▝▘▛▌    ▗▜▝  ▞▘▝▝ ▝▚▐▘▞▌▖▌▝▝▖  ▘ ▄▝▞▖ ▌▌  ▄▝▗ ▖▘ ▜▝  ▖▄▗ ▀ ▐▗▖ ▐
█▗▝▐▖▞▀▝ ▝▗    ▗▗▙▝  ▖ ▗▀ ▗ ▝▝ ▖▝▚▝  ▀ ▚▖ ▐▘▗▐▖  ▝▝▖▙▌▗▖▀▖  ▖▖ ▖ ▗▞▝   ▝ ▖   ▙▝▚ ▘▙ ▘▖▐▝▝▞▗▖▖▖▚▖  ▖█
▌▄  ▗ ▐ ▗  ▝▗▞▘ ▐▐▗    ▘▙▗ ▝ ▝▖▘ ▘▖▀ ▞ ▖ ▘  ▚ ▗▜ ▐   ▖▀ ▄▗▐ ▀ ▚▘ ▗ ▝▗▚ ▗ ▖▌▚▞▝  ▝▞▘  ▐▝ ▝ ▞▗▗ ▚ ▗▘▝▐
▌▖▀ ▗▗▌▄▖ ▄  ▗▖▘▀  ▗▗▗▗▀▘▖ ▚ ▘ ▘▙ ▝▗▝▀▀▟  ▖  ▖▚▖  ▐▀▚ ▝ ▝▗▘▚▝▘▘▖▖▖ ▀ ▖▝▗▐▝  ▝ ▖▗▝ ▖▐▗▌ ▝ ▀▗▝▝ ▖▗ ▘▝▟
▛▞▗▟  ▝▖ ▘▌▞▗▗▄▐▞   ▐▞▖▐▖▖▘ ▖▗▀▖ ▐▚ ▐▖▘ ▟▞▀  ▗▘ ▗▘▗▟▖▄▗▝▖▀ ▛▖ ▚▘▗ ▘ ▌▐▗▖   ▖ ▀█▗▗▝▝▘▖ ▖    ▘▚▘▝▌▖  ▐
▛▝▚▝▗▄▝▐  ▝ ▗▐▞ ▛▘▗▄ ▝     ▝▗▝▐▗▖▖▝   ▀  ▖   ▜▗ ▟▘▚▚▌▝▖  ▝ ▀ ▗▝▖▘▖▖ ▘▀▞  ▖▗▖▗ ▜▗  ▝  ▝█ ▖   ▖▙ ▗▝  ▐
▌▗▝ ▐▝▚▝ ▖ ▖▞▝▞ ▌▖▖▝▝   ▄▟▝▝▐▖ ▖▗▘▄ ▗▖ ▞▘▚▘▗▙▝▐▀▝ ▚▙▗ ▝ ▖▞▖  ▛▝ ▗  ▘▘▗  ▝▖▜▗▞  ▘ ▖▖▄▖ ▛▝▝▝▖▌▌  ▝ ▞▖▐
▙ ▝▘ ▗▄▖ ▘▝▐ ▄ ▘ ▘ ▝▝ ▗▗▘▖  ▄ ▙ ▘ ▗▗▀  ▘ ▘▝▞▗▗▗▖▝▐▝▚▗▘▝ ▐ ▖▌    ▝▖▘▘▌▀▝   ▘  ▀▞▚▝▗ ▝▗▀▗ ▖▚ ▝ ▖▗▖▘▝▌▐
█▙█▄▟█▄▄▟█▄▟▄▄▄▟█▄▟▟▄▙▙▄▄▄▙▟▙▄▄▄▟▙▄▙▙▟▟▄▄▟██▄▄▙▄▄█▄▄▄▄▄▄▟▄▄▙▟▙▄▄▙▄▄▙▄▙▟▙▄▄▙▄▄▄▄▄▟▟▙▄▄▄▄▙▙█▄▄▄▄▟▟▙▟█▄
```

```
200 - 50 - 19
▌▀▜▀▀▛▜█▛▀▜▜▛▜▀▜▀▀▜▛█▛█▀▛▀▛▀▛▜▀▀▀▀▛▀▀▛▀▀█▜█▀▀▀▜▀▛█▀▜▀▜▛▀▀▀▛▀▀▛▜▛▀█▀▛▛▜▛▜▀▀▀▀▀▀▀▛▀▀▀█▛▀▀▜▀▜▀▛▜▀▀▀▀▀▛▜
▌▛▗▌▝▗▚▜  ▖▝▘▚▖▘  ▌   ▖ ▐ ▟ ▞ ▞▌▛▚ ▚ ▜ ▖▗▛▗  ▝▖▝▗▐▝ ▝  ▄▀▘▖▖▗ ▄ ▖ ▝▞▖▝ ▝▗  ▝▞▘▖▚ ▘▖▖▖▝ ▌▘ ▝▝ ▝▖▗▐ ▐▐
▌  ▐ ▗▀▝ ▗▀▚▝▝▚█▗ ▘▖   ▞▝▗▝▞ ▖▀▟▖  ▘▀▀▌▌▞▖▝▖▗▚▀▐ ▄▐▖▝  ▗ ▖ ▀  ▗▞   ▗▖ ▐ ▝▀▜▞▘▖  ▄ ▞ ▗▜ ▝▘▖▝  ▌▄▝▝ ▄▜
▌▗ ▖▀ ▝  ▖▟ ▖▞▝ ▖▝   ▀▚▚  ▖  ▘▄▗▖▄▘▗ ▗▖▘  ▖▗ ▖ ▄▖  ▗▗▞▝▚▌▗▘▛ ▞     ▗▌▌▗    ▘▘ ▝▞▗▌▝  ▜ ▌▘▚ ▖ ▘▞▐ ▘ ▟
▛ ▘▀▖▗ ▘ ▗    ▌▌▌  ▞ ▝▄▘▖▖▟ ▝ ▄      ▝▗▘▖▝ ▖ ▄ ▖▚▚▘▝▘ ▘▝ ▝▖▖▝▖▜▘▝▞▝▗▐▘▗ ▘▚▘ ▛▖▝  ▐ ▌▄ ▀▝▌ ▐▀▖▜▖  ▗▖▐
▛▗ ▝▝▚▖▖▖▖▖  ▖▖▀ ▞▖ ▘▟▞▝ ▘ ▖ ▖▚▘▗  ▘▗█ ▛▗  ▗▘▖  ▝▘▝ ▌▞ ▞▀ ▌▖▖▖ ▝  ▄▜▞▘▚▖▘▖▜▝▝▌▜▟ ▞▗ ▜▘ ▞  ▝ ▘▘  ▝▐ ▐
▙▖▞▖▗ ▗▗ ▘▄ ▌▘▚▘ ▗▝▗▐  ▐▘▜▄ ▐ ▚▝▌▖▄▌▘▀▘ ▝▖ ▝ ▗▝▖▝▟▙▄▝▗▗ ▞ ▝ ▖   ▜▜▞   ▘▘▌▘▝  ▗ ▌▗▖ ▌▚▗▀▚▝▘▀▄▝ ▚ ▚▘▞▟
▌ ▘ ▗▐▘ ▄▚▖▀▗▘▐  ▘▌    ▝▘▘▝▝ ▘▖▐▘▀▚  ▐▝▝▝▝  ▗▘▗▝▀ ▘ ▖▗▖▗▘▙▘▝  ▌▌  ▖ ▘ ▐▜▖▘▝▖▝▗▌▐ ▘▀▝▗▖ ▘▖▖▌   ▗▀ ▖▘▐
▙▞▖▗▗▟▗▗▚▘ ▘▜ ▘  ▚▟▝▝ ▖▀▝▖ ▖▐ ▘▖▝▙▝ ▝▘▘ ▝  ▝▖▐▐ ▚ ▝ ▝▀▄▗▗▀▘  ▝▚▐▌  ▖▗   ▞ ▚▘▗ ▐▀ ▐▘▝ ▐ ▌▘▞▗▗▝▀▗▘▗▖▐█
▌▗   ▝ ▚▗ ▝▚ ▝ ▝▌ ▖▗ ▝ ▀▖ ▌ ▀▄▝▄▀▐ ▖▗▝ ▝▄  ▚▘▌▖▀▖ ▝▚▘ ▀▄▄▘▜▗▗▘▖▗▌▞▗ ▗ ▘  ▘ ▖  ▀▝▘▙▐▖▐  ▟▝ ▞▗▘▘ ▖▘▐▟▐
▌▌▘▌▌▀▖▝▘▝▘▐    ▗▘▞▀▘ ▘▟▗▘▐  ▀  ▗▝▗ ▘▜▝▟  ▀▖▝ ▖ ▝▞▜▗▌▘   ▗▘ ▘▘ ▝▌▖▘▗▘▝      ▘▗▝ ▘▝▖▖▐▘ ▝▝ ▌ ▞▗▌ ▚▝▌▐
▙▗▗▝▖▜ ▝▖ ▐  ▘▗   ▀ ▌▘▚  ▗▘▖▗▚▚▄▀▞▘▚▗▖▝▘ ▄▖ ▘▝▞▄▖▙ ▘▛ ▗▗ ▘▖ ▗ ▟▗  ▗▖ ▞▖     ▄▖▝▘▝ ▜▝ ▘  ▘▝▌ ▘▀▚▘▗ ▟▜
█ ▖▝ ▘ ▚▞ ▘▖▘▝ ▝▗  ▖▞▟▖▚ ▗▖▘▐ ▖▜▘▝▘▝ ▘ ▚▗ ▘▘▜▖▗▀▝▗▌▗▖ ▖▝ ▀▀▞ ▗▌ ▖▞▄▘▟▚ ▗ █▗▘▝      ▀▖ ▚▗▘ ▖▄▝ ▖  ▗▝▐
▌▘ ▖▝▚▄ ▘▗▚▝ ▝ ▝▗▘▘▘▗   ▄▜▗▝▗▝ ▘ ▗▗  ▖▝▙▗▝▘▘ ▟▟  ▀▖▐  ▐▌▜▘ ▘▘  ▖ ▖█▘▙▟ ▀▜ ▘▄ ▜ ▗ ▚▝ ▟▖▀ ▐   ▞▌▗ ▝▞ ▜
▌ ▖    ▖▝▀  ▝▗  ▝▞ ▚▄▀  ▝▖▗▝▖▖  ▝   ▘ ▗▖ ▚ ▚▄  ▘ ▀▘▜▞▗▗▗▐▌  ▖  ▐▝▗▄  ▝▙▜ ▘▘ ▐▗▝▞▘ ▌▘▘ ▖▝ ▘▟▀▗ ▖▗▄▘ ▟
▛ ▞▘▖  ▜▞  ▘▖ ▗ ▝  ▖▗▗▛▖▝ ▘  ▘▞▜  ▗  ▞   ▖▞ ▙▚▌▝ ▝▗ ▞▘▙ ▘▟ ▖▄▗▗   ▝  ▄▘▌ ▝▘▐▝ ▗▘▗  ▝▘▝ ▘▗▖▜▘▌▝▖▚   ▜
▌▘▘▘▐ ▚▚  ▄▄▘  ▝▖▗▘▖ ▝▐▄  ▖▚▖▐  ▖▖ ▞   ▝  ▝▖▖█ ▗▝ ▞ ▛  ▌▝▝▚▝ ▄  ▖   ▝▖ ▗▐▀  ▝▖  ▖▝▌▗▖▗▝▝▗   ▚ ▝▝  ▘▟
▙▝▘▖▖ ▝▄▖▗ ▗▝▝▘ ▘▘ ▝▝   ▘▐▜▖▗▄ ▝ ▘▌▗▀ ▛▝▟▗ ▘ ▝  ▟▝▌▖▘▝▗ ▘ ▝  ▖▀▛▀▗▗ ▄▙   ▝ ▝▛ ▞▝ ▞▗▙  ▘▐▀ ▐▖▝ ▐▘▗▗▝▜
▌  ▝▖▗ ▚▐ ▗▝ ▄▗▘ ▘▝   ▀▘▄▝ ▚ ▐ ▞▀▌ ▀▘▗▟ ▗▀  ▚  ▖▜▗▝▗ ▘ ▐▘    ▗▖▗  ▐▗▞▗▚▌▖ ▐ ▞▘ ▌   ▚   ▖  ▚▘  ▗ ▚ ▗▐
▌▌▐▄ ▄ ▗▘▀ ▘▘ ▗▄ ▝▗▗▘ ▘▌  ▞▐▖   ▚▐▗ ▝▌    ▐▚▘ ▝   ▖ ▝   ▛▝▗▖▗ ▞▗▚▌▖ ▘▝▘▘▘▖  ▄ ▙▝▀▚▄▀▞▚▘  ▄▖▚▗▝▖    █
▛ ▟▌ ▖ ▝▖ ▐▜   ▄▗▐▗  ▝ ▖▗▚▛ ▝ ▛▘▞▌▗▗▜▖▗▗ ▝ ▜▘ ▀ ▘▌ ▐▝▝▗▘▘▘▀▖▟▟▗▝  ▌  ▝▄▖▝▖▘▘▖▚▄▘▖▗▀▗▝ ▄  ▖▘▀▗▝▗ ▗ ▌▐
▛▝▗   ▖▖▝▚▀▝ ▖ ▚▗▖▗   ▐▙▟▘▀▞▟▗ ▚▖  ▗  ▜▟▘▖▌  ▘▗ ▖▖▘▖ ▟▗ ▝▝▗▝▗ ▞▝▘▝ ▘▝  ▘  ▜ ▘  ▘▟▚▝▘▀▞▝ ▘▀▖▘▄▚ ▗  ▞▐
▌▖▘▝▝▗  ▄▖▝▘▗▘█▚ ▗▘▙ ▌ ▚▘▖▝ ▝   ▞▛▐ ▜▗▞ ▞▗▚▝ ▗▟▌ ▀▚ ▘▗▐▜▗ ▖ ▖  ▀▖▗▖▗█▛▝ ▖ ▗▖▞   ▜  ▝▞▛ ▖▝ ▖  ▗ ▄  ▞▐
▛▖▐ ▙▀ ▞▞▖▝  ▄ ▝  ▘▌▀▝▝▖  ▗▐▖  ▖▖▘▚▀ ▟▗▜▘▗▀▜▌▘▐ ▚▝▘▖▝▖ ▖▝▖▖ ▘  ▚ ▀▜▐▝▘▀▖ ▘▗▖ ▖▙▗▘ ▚  ▜ ▖▘ ▖▝▘▛▗ ▘▟▝█
▙▟▄▄▄▟▄▄▄▄▟▙▄█▙█▄▄▄▄▟▄▄▟▟▄▙▟▙▄▄▄▄▟▄▄▟▄▄▄▙▄▙▄▙▄▙▄▄▟▙▄▄▄▄▟▙▙█▄▟▟▟▄▙▄▄▄▄▄▄▟▙▄▟▙▄▙▄▄▟▟▄▄▄▄▄▟▄▄▟▟▄▄▙▄▟▙▄▄
```

2023-04-19 19:33 UTC, felixhauptmann requested changes
Other than that looks fine. I'm passing all tests.

2023-04-19 19:33 UTC, felixhauptmann commented on W01/test/gad/maze/TestExecutor.java
> +    public static String PATH = "test/gad/maze/test-cases.txt";
```suggestion
    public static String PATH = "test/gad/maze/cases.txt";
```

2023-04-19 21:12 UTC, nilsreichardt reviewed
Are we going to use upper case folder names for the tasks (I know that Johannes had set up this folder)?

2023-04-20 04:09 UTC, Anatoly03 commented
@nilsreichardt I believe we can change this in this PR? Or should that be done in another?

2023-04-20 04:18 UTC, Anatoly03 commented
The last two commits rename the folders to lowercase (see [stackoverflow](https://stackoverflow.com/a/30654833/16002144) why two commits are needed), @nilsreichardt

2023-04-20 09:40 UTC, nilsreichardt commented
@JohannesStoehr I think we can this PR because @Anatoly03 fixed @felixhauptmann comment 👍

2023-04-20 10:06 UTC, merged